In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn.init as init

train = pd.read_csv('./train.csv', engine='python')
test = pd.read_csv('./test.csv', engine='python')

In [2]:
# train.iloc[:, 0:5]
train.loc[:5, ['price', 'yr_built']]

price  yr_built
0  221900.0      1955
1  180000.0      1933
2  510000.0      1987
3  257500.0      1995
4  291850.0      1963
5  662500.0      1965

In [3]:
train[['bedrooms', 'price']][:5]

bedrooms     price
0         3  221900.0
1         2  180000.0
2         3  510000.0
3         3  257500.0
4         3  291850.0

In [364]:
train.loc[:, ['yr_built']][:5]

yr_built
0      1955
1      1933
2      1987
3      1995
4      1963

In [365]:
a = train['yr_built'].apply(lambda x: 2019-x)
# b = train['yr_renovated'].apply(lambda x: 0 if x==0 else 2019-x)
# train.loc[:, ['yr_built', 'yr_renovated']] = [a,b]
# train
train

id             date      price  bedrooms  bathrooms  sqft_living  \
0          0  20141013T000000   221900.0         3       1.00         1180   
1          1  20150225T000000   180000.0         2       1.00          770   
2          2  20150218T000000   510000.0         3       2.00         1680   
3          3  20140627T000000   257500.0         3       2.25         1715   
4          4  20150115T000000   291850.0         3       1.50         1060   
5          5  20150403T000000   662500.0         3       2.50         3560   
6          6  20140527T000000   468000.0         2       1.00         1160   
7          7  20140528T000000   310000.0         3       1.00         1430   
8          8  20141007T000000   400000.0         3       1.75         1370   
9          9  20150312T000000   530000.0         5       2.00         1810   
10        10  20150124T000000   650000.0         4       3.00         2950   
11        11  20140731T000000   395000.0         3       2.00         1890   
12        12  20140529T000000   485000.0         4       1.00         1600   
13        13  20141205T000000   189000.0         2       1.00         1200   
14        14  20150424T000000   230000.0         3       1.00         1250   
15        15  20140514T000000   385000.0         4       1.75         1620   
16        16  20140826T000000  2000000.0         3       2.75         3050   
17        17  20140516T000000   252700.0         2       1.50         1070   
18        18  20141120T000000   329000.0         3       2.25         2450   
19        19  20141103T000000   233000.0         3       2.00         1710   
20        20  20140626T000000   937000.0         3       1.75         2450   
21        21  20141201T000000   667000.0         3       1.00         1400   
22        22  20141110T000000   580500.0         3       2.50         2320   
23        23  20140624T000000   687500.0         4       1.75         2330   
24        24  20141110T000000   535000.0         3       1.00         1090   
25        25  20141203T000000   322500.0         4       2.75         2060   
26        26  20140613T000000   696000.0         3       2.50         2300   
27        27  20141230T000000   640000.0         4       2.00         2360   
28        28  20150213T000000   240000.0         4       1.00         1220   
29        29  20140620T000000   605000.0         4       2.50         2620   
...      ...              ...        ...       ...        ...          ...   
15005  15005  20140513T000000   330000.0         3       2.50         1450   
15006  15006  20150502T000000   608500.0         4       3.50         2850   
15007  15007  20140520T000000   785000.0         4       3.50         3070   
15008  15008  20140507T000000   610950.0         3       3.00         1680   
15009  15009  20141111T000000   399950.0         3       2.50         3087   
15010  15010  20150123T000000   579000.0         4       3.25         1900   
15011  15011  20140623T000000   362500.0         2       1.50          940   
15012  15012  20140529T000000   645000.0         3       3.25         1730   
15013  15013  20141003T000000   594866.0         3       3.00         2780   
15014  15014  20141112T000000   490000.0         3       2.25         1500   
15015  15015  20140610T000000   399950.0         2       1.00          710   
15016  15016  20140828T000000   270000.0         3       2.50         1870   
15017  15017  20141015T000000   505000.0         2       2.50         1430   
15018  15018  20150305T000000   385000.0         3       2.50         1520   
15019  15019  20141113T000000   414500.0         2       1.50         1210   
15020  15020  20140910T000000   347500.0         3       2.50         2540   
15021  15021  20140514T000000  1222500.0         4       3.50         4910   
15022  15022  20150317T000000  1088000.0         5       3.75         4170   
15023  15023  20141017T000000   350000.0         4       2.75         2500   
15024  15024  20140813T000000   

In [106]:
train.drop(['date', 'id', 'zipcode', 'lat', 'long', 'condition', 'price'], axis=1)[:5]

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0         3       1.00         1180      5650     1.0           0     0   
1         2       1.00          770     10000     1.0           0     0   
2         3       2.00         1680      8080     1.0           0     0   
3         3       2.25         1715      6819     2.0           0     0   
4         3       1.50         1060      9711     1.0           0     0   

   grade  sqft_above  sqft_basement  yr_built  yr_renovated  sqft_living15  \
0      7        1180              0      1955             0           1340   
1      6         770              0      1933             0           2720   
2      8        1680              0      1987             0           1800   
3      7        1715              0      1995             0           2238   
4      7        1060              0      1963             0           1650   

   sqft_lot15  
0        5650  
1        8062  
2        7503  
3        6819  
4        9711

In [2]:
def dataset(df):
    y = df[['price']]
    df = df.drop(['date', 'id', 'zipcode', 'lat', 'long', 'condition', 'price'], axis=1)
    changed_built = df['yr_built'].apply(lambda x: 2019-x)
    changed_renovate = df['yr_renovated'].apply(lambda x: 0 if x==0 else 2019-x)
    df.loc[:, ['yr_built']] = changed_built
    df.loc[:, ['yr_renovated']] = changed_renovate
    return df, y

In [3]:
x, y = dataset(train)
x[0:10]

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0         3       1.00         1180      5650     1.0           0     0   
1         2       1.00          770     10000     1.0           0     0   
2         3       2.00         1680      8080     1.0           0     0   
3         3       2.25         1715      6819     2.0           0     0   
4         3       1.50         1060      9711     1.0           0     0   
5         3       2.50         3560      9796     1.0           0     0   
6         2       1.00         1160      6000     1.0           0     0   
7         3       1.00         1430     19901     1.5           0     0   
8         3       1.75         1370      9680     1.0           0     0   
9         5       2.00         1810      4850     1.5           0     0   

   grade  sqft_above  sqft_basement  yr_built  yr_renovated  sqft_living15  \
0      7        1180              0        64             0           1340   
1      6         770              0        86             0           2720   
2      8        1680              0        32             0           1800   
3      7        1715              0        24             0           2238   
4      7        1060              0        56             0           1650   
5      8        1860           1700        54             0           2210   
6      7         860            300        77             0           1330   
7      7        1430              0        92             0           1780   
8      7        1370              0        42             0           1370   
9      7        1810              0       119             0           1360   

   sqft_lot15  
0        5650  
1        8062  
2        7503  
3        6819  
4        9711  
5        8925  
6        6000  
7       12697  
8       10208  
9        4850

In [369]:
x = torch.from_numpy(x.values).float()
y = torch.from_numpy(y.values).float()

In [316]:
x[:5]

tensor([[3.0000e+00, 1.0000e+00, 1.1800e+03, 5.6500e+03, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 7.0000e+00, 1.1800e+03, 0.0000e+00, 6.4000e+01, 0.0000e+00,
         1.3400e+03, 5.6500e+03],
        [2.0000e+00, 1.0000e+00, 7.7000e+02, 1.0000e+04, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 6.0000e+00, 7.7000e+02, 0.0000e+00, 8.6000e+01, 0.0000e+00,
         2.7200e+03, 8.0620e+03],
        [3.0000e+00, 2.0000e+00, 1.6800e+03, 8.0800e+03, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 8.0000e+00, 1.6800e+03, 0.0000e+00, 3.2000e+01, 0.0000e+00,
         1.8000e+03, 7.5030e+03],
        [3.0000e+00, 2.2500e+00, 1.7150e+03, 6.8190e+03, 2.0000e+00, 0.0000e+00,
         0.0000e+00, 7.0000e+00, 1.7150e+03, 0.0000e+00, 2.4000e+01, 0.0000e+00,
         2.2380e+03, 6.8190e+03],
        [3.0000e+00, 1.5000e+00, 1.0600e+03, 9.7110e+03, 1.0000e+00, 0.0000e+00,
         0.0000e+00, 7.0000e+00, 1.0600e+03, 0.0000e+00, 5.6000e+01, 0.0000e+00,
         1.6500e+03, 9.7110e+03]])

In [370]:
y.shape

torch.Size([15035, 1])

In [371]:
y[:5]

tensor([[221900.],
        [180000.],
        [510000.],
        [257500.],
        [291850.]])

In [27]:
N, D_in, H, D_out = 4096,14,100,1

In [224]:
class OneLayerNet(torch.nn.Module):
    def __init__(self, D_in, D_out):
        super(OneLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, D_out)

    def forward(self, x):
        y_pred = self.linear1(x)
        return y_pred

In [225]:
class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)

    def forward(self, x):
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred

In [20]:
class TLN(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        super(TLN, self).__init__()
        self.linear1 = torch.nn.Sequential(torch.nn.Linear(D_in, H, bias=False), torch.nn.BatchNorm1d(H))
        self.linear2 = torch.nn.Sequential(torch.nn.Linear(H, H, bias=False), torch.nn.BatchNorm1d(H))
        self.linear3 = torch.nn.Sequential(torch.nn.Linear(H, H, bias=False), torch.nn.BatchNorm1d(H))
        self.linear4 = torch.nn.Linear(H, D_out)

    def forward(self, x):
        h_relu = self.linear1(x).clamp(min=0)
        h_relu2 = self.linear2(h_relu).clamp(min=0)
        h_relu3 = self.linear3(h_relu2).clamp(min=0)
        y_pred = self.linear4(h_relu3)
        return y_pred

In [21]:
def weight_init(m):
    '''
    Usage:
        model = Model()
        model.apply(weight_init)
    '''
    if isinstance(m, torch.nn.Conv2d):
        init.xavier_normal_(m.weight.data)
        if m.bias is not None:
            init.zeros_(m.bias.data)
    elif isinstance(m, torch.nn.Linear):
        init.xavier_normal_(m.weight.data)
        if m.bias is not None:
            init.zeros_(m.bias.data)

In [28]:
model = TLN(D_in, H, D_out)
model.apply(weight_init)
# model = TwoLayerNet(D_in, H, D_out)

TLN(
  (linear1): Sequential(
    (0): Linear(in_features=14, out_features=100, bias=False)
    (1): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (linear2): Sequential(
    (0): Linear(in_features=100, out_features=100, bias=False)
    (1): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (linear3): Sequential(
    (0): Linear(in_features=100, out_features=100, bias=False)
    (1): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (linear4): Linear(in_features=100, out_features=1, bias=True)
)

In [54]:
criterion = torch.nn.MSELoss(reduction='mean')
# optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

In [44]:
x, y = dataset(train)
x = torch.from_numpy(x.values).float()
y = torch.from_numpy(y.values).float()

In [45]:
N = 256

In [55]:
for t in range(500):
    model.train()
    index = np.random.choice(15035, N, replace=False)
    y_pred = model(x)
    loss = criterion(y_pred, y)*1e-5
    if t % 10 == 0:
#         print(y_pred[0])
#         print(y[index][0])
        print(t, loss.item())
    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 454032.28125
10 451632.6875
20 448021.03125
30 445015.5625
40 442333.75
50 439912.1875
60 437395.15625
70 434866.0
80 433025.90625
90 430474.875
100 427435.1875
110 424330.53125
120 421242.71875
130 417684.59375
140 414273.53125
150 411486.65625
160 409738.28125
170 408986.03125
180 404060.9375
190 401918.46875
200 400190.75
210 399632.9375
220 397113.0
230 391722.78125
240 395513.4375
250 389810.125
260 387860.71875
270 383510.96875
280 381181.375
290 382272.71875
300 378406.0
310 381687.09375
320 375678.28125
330 372085.625
340 373822.09375
350 376409.3125
360 367181.3125
370 369205.53125
380 368768.59375
390 365326.375
400 364519.375
410 370472.5
420 363049.3125
430 359474.09375
440 362395.84375
450 358083.4375
460 355257.25
470 357321.9375
480 352600.78125
490 347999.90625


In [57]:
model(x).shape

torch.Size([15035, 1])

In [58]:
model(x)

tensor([[367803.7188],
        [330828.6562],
        [352604.9062],
        ...,
        [495495.8750],
        [426194.7500],
        [350660.1250]], grad_fn=<AddmmBackward>)

In [62]:
def testset(df):
    df = df.drop(['date', 'id', 'zipcode', 'lat', 'long', 'condition'], axis=1)
    changed_built = df['yr_built'].apply(lambda x: 2019-x)
    changed_renovate = df['yr_renovated'].apply(lambda x: 0 if x==0 else 2019-x)
    df.loc[:, ['yr_built']] = changed_built
    df.loc[:, ['yr_renovated']] = changed_renovate
    return df

In [66]:
x_test = testset(test)
x_test = torch.from_numpy(x_test.values).float()

In [73]:
ret = model(x_test)

In [78]:
np.set_printoptions(formatter={'float_kind':'{:f}'.format})

In [80]:
myfile = open('./result','ab')
np.savetxt("result.txt", ret.detach().numpy(), fmt='%f')
myfile.close()

In [229]:
model_one_layer = OneLayerNet(D_in, D_out)
model_two_layer = TwoLayerNet(D_in, H, D_out)

In [228]:
model_one_layer.forward(x)

tensor([[ -11.6816],
        [ 683.5372],
        [ 119.6052],
        ...,
        [ -54.4877],
        [-400.4066],
        [ -48.3118]], grad_fn=<AddmmBackward>)

In [236]:
model_two_layer.forward(x)

tensor([[283.6677],
        [328.0321],
        [401.4743],
        ...,
        [241.4504],
        [474.9030],
        [175.9978]], grad_fn=<AddmmBackward>)

In [237]:
y

tensor([[221900.],
        [180000.],
        [510000.],
        ...,
        [360000.],
        [400000.],
        [325000.]])

In [233]:
loss = criterion(model_one_layer.forward(x), y)
loss

tensor(6.4621e+15, grad_fn=<MseLossBackward>)

In [227]:
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model_one_layer.parameters(), lr=1e-10)

In [250]:
criterion = torch.nn.MSELoss(reduction='mean')
optimizer = torch.optim.SGD(model_two_layer.parameters(), lr=1e-30)

In [251]:
for t in range(500):
    y_pred = model_two_layer(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 nan
1 nan
2 nan
3 nan
4 nan
5 nan
6 nan
7 nan
8 nan
9 nan
10 nan
11 nan
12 nan
13 nan
14 nan
15 nan
16 nan
17 nan
18 nan
19 nan
20 nan
21 nan
22 nan
23 nan
24 nan
25 nan
26 nan
27 nan
28 nan
29 nan
30 nan
31 nan
32 nan
33 nan
34 nan
35 nan
36 nan
37 nan
38 nan
39 nan
40 nan
41 nan
42 nan
43 nan
44 nan
45 nan
46 nan
47 nan
48 nan
49 nan
50 nan
51 nan
52 nan
53 nan
54 nan
55 nan
56 nan
57 nan
58 nan
59 nan
60 nan
61 nan
62 nan
63 nan
64 nan
65 nan
66 nan
67 nan
68 nan
69 nan
70 nan
71 nan
72 nan
73 nan
74 nan
75 nan
76 nan
77 nan
78 nan
79 nan
80 nan
81 nan
82 nan
83 nan
84 nan
85 nan
86 nan
87 nan
88 nan
89 nan
90 nan
91 nan
92 nan
93 nan
94 nan
95 nan
96 nan
97 nan
98 nan
99 nan
100 nan
101 nan
102 nan
103 nan
104 nan
105 nan
106 nan
107 nan
108 nan
109 nan
110 nan
111 nan
112 nan
113 nan
114 nan
115 nan
116 nan
117 nan
118 nan
119 nan
120 nan
121 nan
122 nan
123 nan
124 nan
125 nan
126 nan
127 nan
128 nan
129 nan
130 nan
131 nan
132 nan
133 nan
134 nan
135 nan
136 nan
137 nan
138 na