In [4]:
# import tensorflow as tf
x1_data = [73., 93., 89., 96., 63.]
x1_data = [80., 88., 91., 98., 66.]
x1_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [ ]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

In [1]:
import numpy as np

In [8]:
xy = np.loadtxt('/Users/essemfly/Desktop/DeepLearningZeroToAll/data-01-test-score.csv', delimiter=',', dtype=np.float32)

In [9]:
x_data = xy[:, 0:-1]

In [12]:
x_data

array([[  73.,   80.,   75.],
       [  93.,   88.,   93.],
       [  89.,   91.,   90.],
       [  96.,   98.,  100.],
       [  73.,   66.,   70.],
       [  53.,   46.,   55.],
       [  69.,   74.,   77.],
       [  47.,   56.,   60.],
       [  87.,   79.,   90.],
       [  79.,   70.,   88.],
       [  69.,   70.,   73.],
       [  70.,   65.,   74.],
       [  93.,   95.,   91.],
       [  79.,   80.,   73.],
       [  70.,   73.,   78.],
       [  93.,   89.,   96.],
       [  78.,   75.,   68.],
       [  81.,   90.,   93.],
       [  88.,   92.,   86.],
       [  78.,   83.,   77.],
       [  82.,   86.,   90.],
       [  86.,   82.,   89.],
       [  78.,   83.,   85.],
       [  76.,   83.,   71.],
       [  96.,   93.,   95.]], dtype=float32)

In [14]:
y_data = xy[:, [-1]]

In [15]:
y_data

array([[ 152.],
       [ 185.],
       [ 180.],
       [ 196.],
       [ 142.],
       [ 101.],
       [ 149.],
       [ 115.],
       [ 175.],
       [ 164.],
       [ 141.],
       [ 141.],
       [ 184.],
       [ 152.],
       [ 148.],
       [ 192.],
       [ 147.],
       [ 183.],
       [ 177.],
       [ 159.],
       [ 177.],
       [ 175.],
       [ 175.],
       [ 149.],
       [ 192.]], dtype=float32)

In [16]:
print(x_data.shape, x_data, len(x_data))

(25, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]] 25


In [17]:
print(y_data.shape, y_data)

(25, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]


In [18]:
import tensorflow as tf

In [19]:
tf.set_random_seed(777)

In [20]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [21]:
hypothesis = tf.matmul(X, W) + b

In [22]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [23]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

In [24]:
train = optimizer.minimize(cost)

In [25]:
sess = tf.Session()

In [26]:
sess.run(tf.global_variables_initializer())

In [27]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  21027.0 
Prediction:
 [[ 22.04806328]
 [ 21.61978722]
 [ 24.09669304]
 [ 22.29300499]
 [ 18.6339016 ]
 [  7.2669735 ]
 [ 12.33102989]
 [  3.15051103]
 [ 14.34794426]
 [  4.25342369]
 [ 14.48570824]
 [ 10.67806816]
 [ 28.80463982]
 [ 29.29880333]
 [ 11.23783684]
 [ 18.6465435 ]
 [ 31.18945122]
 [ 13.34466362]
 [ 28.84174156]
 [ 25.66280937]
 [ 15.08476067]
 [ 16.79836845]
 [ 15.92455101]
 [ 31.36112022]
 [ 24.98636436]]
10 Cost:  95.9763 
Prediction:
 [[ 157.11062622]
 [ 183.99281311]
 [ 184.0630188 ]
 [ 196.5291748 ]
 [ 142.46273804]
 [  98.59757233]
 [ 142.77235413]
 [  99.87779999]
 [ 166.13175964]
 [ 144.89149475]
 [ 140.14994812]
 [ 134.61138916]
 [ 194.0514679 ]
 [ 166.64041138]
 [ 142.2870636 ]
 [ 183.4329834 ]
 [ 161.97666931]
 [ 169.89073181]
 [ 186.37145996]
 [ 166.61376953]
 [ 168.04634094]
 [ 169.14367676]
 [ 161.75204468]
 [ 167.48861694]
 [ 193.25117493]]
20 Cost:  94.2573 
Prediction:
 [[ 158.01502991]
 [ 185.11975098]
 [ 185.15112305]
 [ 197.73497009]
 [ 143.315

430 Cost:  69.3932 
Prediction:
 [[ 156.95353699]
 [ 185.30467224]
 [ 184.51647949]
 [ 197.82434082]
 [ 143.17510986]
 [ 100.53486633]
 [ 144.51281738]
 [ 102.20146179]
 [ 168.68511963]
 [ 149.16230774]
 [ 141.45106506]
 [ 136.86386108]
 [ 193.72503662]
 [ 165.32310486]
 [ 144.34838867]
 [ 185.3895874 ]
 [ 160.21443176]
 [ 172.13792419]
 [ 185.70169067]
 [ 165.99766541]
 [ 170.01742554]
 [ 171.06097412]
 [ 163.27560425]
 [ 165.47619629]
 [ 193.99716187]]
440 Cost:  68.8872 
Prediction:
 [[ 156.93014526]
 [ 185.30822754]
 [ 184.50222778]
 [ 197.82626343]
 [ 143.17131042]
 [ 100.56268311]
 [ 144.53128052]
 [ 102.23803711]
 [ 168.71710205]
 [ 149.23329163]
 [ 141.46040344]
 [ 136.89370728]
 [ 193.69302368]
 [ 165.27366638]
 [ 144.37358093]
 [ 185.40689087]
 [ 160.1559906 ]
 [ 172.16377258]
 [ 185.66351318]
 [ 165.96324158]
 [ 170.03742981]
 [ 171.07929993]
 [ 163.28701782]
 [ 165.4122467 ]
 [ 193.98765564]]
450 Cost:  68.3854 
Prediction:
 [[ 156.90687561]
 [ 185.31175232]
 [ 184.48805237

860 Cost:  51.0304 
Prediction:
 [[ 156.04786682]
 [ 185.4302063 ]
 [ 183.95805359]
 [ 197.90403748]
 [ 143.00506592]
 [ 101.61300659]
 [ 145.25506592]
 [ 103.6700592 ]
 [ 169.92469788]
 [ 151.93977356]
 [ 141.82157898]
 [ 138.0287323 ]
 [ 192.46437073]
 [ 163.37220764]
 [ 145.35154724]
 [ 186.0606842 ]
 [ 157.89756775]
 [ 173.18197632]
 [ 184.20343018]
 [ 164.65063477]
 [ 170.81726074]
 [ 171.77287292]
 [ 163.73905945]
 [ 162.96884155]
 [ 193.61216736]]
870 Cost:  50.6766 
Prediction:
 [[ 156.02906799]
 [ 185.43252563]
 [ 183.94630432]
 [ 197.90582275]
 [ 143.0009613 ]
 [ 101.63540649]
 [ 145.27111816]
 [ 103.70181274]
 [ 169.95043945]
 [ 151.99807739]
 [ 141.82946777]
 [ 138.05310059]
 [ 192.43769836]
 [ 163.33082581]
 [ 145.37298584]
 [ 186.07463074]
 [ 157.84817505]
 [ 173.20471191]
 [ 184.171875  ]
 [ 164.62236023]
 [ 170.83447266]
 [ 171.78768921]
 [ 163.74920654]
 [ 162.9160614 ]
 [ 193.60375977]]
880 Cost:  50.3257 
Prediction:
 [[ 156.01040649]
 [ 185.43478394]
 [ 183.93463135

1330 Cost:  37.1882 
Prediction:
 [[ 155.26199341]
 [ 185.51278687]
 [ 183.45884705]
 [ 197.98501587]
 [ 142.80793762]
 [ 102.55170441]
 [ 145.95666504]
 [ 105.05590057]
 [ 171.003479  ]
 [ 154.41177368]
 [ 142.16207886]
 [ 139.05731201]
 [ 191.32632446]
 [ 161.6010437 ]
 [ 146.27893066]
 [ 186.6452179 ]
 [ 155.77069092]
 [ 174.18066406]
 [ 182.8609314 ]
 [ 163.45173645]
 [ 171.56509399]
 [ 172.39471436]
 [ 164.18684387]
 [ 160.72613525]
 [ 193.24177551]]
1340 Cost:  36.9479 
Prediction:
 [[ 155.24726868]
 [ 185.51405334]
 [ 183.44934082]
 [ 197.98666382]
 [ 142.80366516]
 [ 102.56932831]
 [ 145.9704895 ]
 [ 105.08315277]
 [ 171.02374268]
 [ 154.45880127]
 [ 142.16868591]
 [ 139.07679749]
 [ 191.30450439]
 [ 161.56697083]
 [ 146.29698181]
 [ 186.65618896]
 [ 155.72949219]
 [ 174.20045471]
 [ 182.83529663]
 [ 163.42892456]
 [ 171.57974243]
 [ 172.40643311]
 [ 164.195755  ]
 [ 160.68334961]
 [ 193.23443604]]
1350 Cost:  36.7095 
Prediction:
 [[ 155.2326355 ]
 [ 185.51525879]
 [ 183.43984

1790 Cost:  27.9306 
Prediction:
 [[ 154.65890503]
 [ 185.55166626]
 [ 183.06211853]
 [ 198.05812073]
 [ 142.61053467]
 [ 103.27503204]
 [ 146.54859924]
 [ 106.22309875]
 [ 171.83432007]
 [ 156.3664856 ]
 [ 142.44111633]
 [ 139.86320496]
 [ 190.41194153]
 [ 160.16900635]
 [ 147.0435791 ]
 [ 187.0958252 ]
 [ 154.03009033]
 [ 175.03330994]
 [ 181.79119873]
 [ 162.50369263]
 [ 172.18904114]
 [ 172.8757782 ]
 [ 164.57287598]
 [ 158.94268799]
 [ 192.92378235]]
1800 Cost:  27.7653 
Prediction:
 [[ 154.64735413]
 [ 185.55213928]
 [ 183.05438232]
 [ 198.05966187]
 [ 142.60624695]
 [ 103.28892517]
 [ 146.56053162]
 [ 106.24662018]
 [ 171.8502655 ]
 [ 156.40454102]
 [ 142.44665527]
 [ 139.87882996]
 [ 190.39398193]
 [ 160.14077759]
 [ 147.05882263]
 [ 187.10449219]
 [ 153.99554443]
 [ 175.0506134 ]
 [ 181.77027893]
 [ 162.48524475]
 [ 172.20155334]
 [ 172.88504028]
 [ 164.58074951]
 [ 158.90783691]
 [ 192.91732788]]
1810 Cost:  27.6012 
Prediction:
 [[ 154.63586426]
 [ 185.55258179]
 [ 183.04666

In [28]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

Your score will be  [[ 181.73277283]]


In [ ]:
filename_queue = tf.train.string_input_producer(
[])