In [16]:
import gym
import tensorflow as tf
import numpy as np

In [17]:
env = gym.make('CartPole-v0')
env.reset()

[2017-07-28 15:22:38,991] Making new env: CartPole-v0


array([ 0.01818934, -0.01173276, -0.04890503, -0.02562905])

In [18]:
for _ in range(100):
    env.render()
    env.step(env.action_space.sample())

[2017-07-28 15:22:40,075] You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


In [19]:
random_episodes = 0
reward_sum = 0

In [21]:
dis = .99
num_episodes = 2000
learning_rate = 0.1
input_size = env.observation_space.shape[0]
output_size = env.action_space.n
rList = []

In [15]:
X = tf.placeholder(tf.float32, [None, input_size], name="input_x")
W1 = tf.get_variable("W1", shape=[input_size, output_size], initializer=tf.contrib.layers.xavier_initializer())
Qpred = tf.matmul(X, W1)
Y = tf.placeholder(shape=[None, output_size], dtype=tf.float32)
loss = tf.reduce_sum(tf.square(Y-Qpred))
train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)

ValueError: Variable W1 already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "<ipython-input-12-e9122ee5edab>", line 4, in <module>
    W1 = tf.get_variable("W1", shape=[input_size, output_size], initializer=tf.contrib.layers.xavier_initializer())
  File "/Users/essemfly/.pyenv/versions/3.6.1/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/Users/essemfly/.pyenv/versions/3.6.1/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):


In [7]:
while random_episodes < 50:
    env.render()
    action = env.action_space.sample()
    observation, reward, done, _ = env.step(action)
    print(observation, reward, done)
    reward_sum += reward
    if done:
        random_episodes += 1
        print("Reward for this episode was:", reward_sum)
        reward_sum = 0
        env.reset()

[-0.00922436  0.19520776  0.02105398 -0.2595297 ] 1.0 False
[-0.00532021  0.39002292  0.01586339 -0.54549826] 1.0 False
[ 0.00248025  0.1946817   0.00495342 -0.24785966] 1.0 False
[  6.37388554e-03  -5.10638032e-04  -3.76829280e-06   4.63815596e-02] 1.0 False
[ 0.00636367 -0.19563254  0.00092386  0.3390633 ] 1.0 False
[ 0.00245102 -0.39076762  0.00770513  0.63203742] 1.0 False
[-0.00536433 -0.19575401  0.02034588  0.34179097] 1.0 False
[-0.00927941 -0.00092735  0.0271817   0.05559274] 1.0 False
[-0.00929796  0.19379452  0.02829355 -0.22839174] 1.0 False
[-0.00542207 -0.00172009  0.02372572  0.07308   ] 1.0 False
[-0.00545647  0.19305383  0.02518732 -0.21202395] 1.0 False
[-0.00159539  0.38780677  0.02094684 -0.49665642] 1.0 False
[ 0.00616074  0.58262719  0.01101371 -0.78266502] 1.0 False
[ 0.01781329  0.77759605 -0.00463959 -1.07186261] 1.0 False
[ 0.03336521  0.97277904 -0.02607684 -1.36599797] 1.0 False
[ 0.05282079  1.16821761 -0.0533968  -1.66672188] 1.0 False
[ 0.07618514  1.3639

[ 0.01060128 -0.34547757 -0.13374774  0.25007475] 1.0 False
[ 0.00369173 -0.53846122 -0.12874625  0.49776024] 1.0 False
[-0.00707749 -0.73155523 -0.11879105  0.74725716] 1.0 False
[-0.0217086  -0.92485544 -0.1038459   1.0003216 ] 1.0 False
[-0.04020571 -1.11844775 -0.08383947  1.25866986] 1.0 False
[-0.06257466 -1.31240286 -0.05866607  1.52396069] 1.0 False
[-0.08882272 -1.50676934 -0.02818686  1.79777091] 1.0 False
[-0.11895811 -1.31134359  0.00776856  1.49646288] 1.0 False
[-0.14518498 -1.50655911  0.03769782  1.79156127] 1.0 False
[-0.17531616 -1.31187951  0.07352904  1.51082986] 1.0 False
[-0.20155375 -1.11772135  0.10374564  1.24197762] 1.0 False
[-0.22390818 -1.31401063  0.12858519  1.56527498] 1.0 False
[-0.25018839 -1.12063866  0.15989069  1.31531161] 1.0 False
[-0.27260116 -0.92785972  0.18619692  1.07663947] 1.0 False
[-0.29115836 -0.73561953  0.20772971  0.8476895 ] 1.0 False
[-0.30587075 -0.93287715  0.2246835   1.19784913] 1.0 True
Reward for this episode was: 47.0
[-0.027

[ 0.01451276 -0.23591549 -0.01639955  0.30552487] 1.0 False
[ 0.00979445 -0.04056373 -0.01028905  0.00771538] 1.0 False
[ 0.00898318 -0.23553662 -0.01013474  0.29713431] 1.0 False
[ 0.00427245 -0.43051264 -0.00419206  0.58660375] 1.0 False
[-0.00433781 -0.23533223  0.00754002  0.29260325] 1.0 False
[-0.00904445 -0.04031859  0.01339208  0.00230785] 1.0 False
[-0.00985082  0.15460876  0.01343824 -0.28611981] 1.0 False
[-0.00675865  0.34953651  0.00771584 -0.57453431] 1.0 False
[  2.32083789e-04   1.54307243e-01  -3.77484386e-03  -2.79430689e-01] 1.0 False
[ 0.00331823 -0.04076066 -0.00936346  0.01205927] 1.0 False
[ 0.00250302  0.15449432 -0.00912227 -0.28356317] 1.0 False
[ 0.0055929  -0.04049634 -0.01479354  0.00622874] 1.0 False
[ 0.00478298  0.15483461 -0.01466896 -0.29108477] 1.0 False
[ 0.00787967  0.35016262 -0.02049066 -0.58835778] 1.0 False
[ 0.01488292  0.54556543 -0.03225781 -0.8874243 ] 1.0 False
[ 0.02579423  0.74111002 -0.0500063  -1.19007074] 1.0 False
[ 0.04061643  0.5466

[-0.01850827 -0.3847858  -0.12583937  0.11683941] 1.0 False
[-0.02620399 -0.57790111 -0.12350258  0.36732263] 1.0 False
[-0.03776201 -0.38126047 -0.11615613  0.0383908 ] 1.0 False
[-0.04538722 -0.57454173 -0.11538832  0.29228587] 1.0 False
[-0.05687805 -0.7678456  -0.1095426   0.54646458] 1.0 False
[-0.07223497 -0.96127178 -0.09861331  0.80272366] 1.0 False
[-0.0914604  -0.76494586 -0.08255883  0.48072017] 1.0 False
[-0.10675932 -0.9588113  -0.07294443  0.74628311] 1.0 False
[-0.12593554 -0.76276272 -0.05801877  0.43156561] 1.0 False
[-0.1411908  -0.9570172  -0.04938746  0.70540911] 1.0 False
[-0.16033114 -1.15142132 -0.03527927  0.98214571] 1.0 False
[-0.18335957 -1.34605321 -0.01563636  1.26354192] 1.0 False
[-0.21028063 -1.54097181  0.00963448  1.55128719] 1.0 False
[-0.24110007 -1.34596673  0.04066022  1.26162564] 1.0 False
[-0.2680194  -1.15138767  0.06589274  0.98194909] 1.0 False
[-0.29104716 -0.95720764  0.08553172  0.71066959] 1.0 False
[-0.31019131 -1.15340341  0.09974511  1.

[-0.03925954  0.53835039 -0.01167125 -0.70653379] 1.0 False
[-0.02849253  0.34339206 -0.02580193 -0.41754749] 1.0 False
[-0.02162469  0.14864508 -0.03415288 -0.13310917] 1.0 False
[-0.01865179  0.34423918 -0.03681506 -0.43636822] 1.0 False
[-0.011767    0.5398624  -0.04554242 -0.74042541] 1.0 False
[ -9.69754544e-04   7.35582565e-01  -6.03509325e-02  -1.04708609e+00] 1.0 False
[ 0.0137419   0.54131123 -0.08129265 -0.77394202] 1.0 False
[ 0.02456812  0.34739611 -0.09677149 -0.50790365] 1.0 False
[ 0.03151604  0.54373883 -0.10692957 -0.82944621] 1.0 False
[ 0.04239082  0.74014731 -0.12351849 -1.15375367] 1.0 False
[ 0.05719377  0.54683354 -0.14659357 -0.90221438] 1.0 False
[ 0.06813044  0.35396906 -0.16463785 -0.65896486] 1.0 False
[ 0.07520982  0.16147473 -0.17781715 -0.42231295] 1.0 False
[ 0.07843931  0.35861134 -0.18626341 -0.76535842] 1.0 False
[ 0.08561154  0.55574272 -0.20157058 -1.11038617] 1.0 False
[ 0.09672639  0.36375617 -0.2237783  -0.88709823] 1.0 True
Reward for this episo

[-0.06850086 -0.02900199  0.10147941  0.09368424] 1.0 False
[-0.0690809  -0.22542097  0.1033531   0.41658073] 1.0 False
[-0.07358932 -0.03190397  0.11168471  0.15818593] 1.0 False
[-0.0742274  -0.22843301  0.11484843  0.48390994] 1.0 False
[-0.07879606 -0.42497257  0.12452663  0.81046839] 1.0 False
[-0.08729551 -0.62156051  0.140736    1.13958318] 1.0 False
[-0.09972672 -0.81821343  0.16352766  1.47288604] 1.0 False
[-0.11609099 -1.014913    0.19298538  1.81186232] 1.0 False
[-0.13638925 -0.82239443  0.22922263  1.58483149] 1.0 True
Reward for this episode was: 16.0
[ 0.0197605  -0.23300508  0.03854025  0.3518877 ] 1.0 False
[ 0.01510039 -0.4286533   0.04557801  0.65647013] 1.0 False
[ 0.00652733 -0.62437912  0.05870741  0.96314926] 1.0 False
[-0.00596025 -0.43009302  0.07797039  0.68947225] 1.0 False
[-0.01456211 -0.23613473  0.09175984  0.42231881] 1.0 False
[-0.01928481 -0.43242874  0.10020622  0.74246066] 1.0 False
[-0.02793338 -0.23882226  0.11505543  0.48291912] 1.0 False
[-0.032

[-0.18264518 -0.80389372  0.20134311  1.53189179] 1.0 False
[-0.19872305 -1.00079175  0.23198095  1.88006823] 1.0 True
Reward for this episode was: 21.0
[ 0.0250609   0.1727176  -0.0262518  -0.31390668] 1.0 False
[ 0.02851525 -0.02202074 -0.03252993 -0.02961696] 1.0 False
[ 0.02807484  0.17355224 -0.03312227 -0.33238335] 1.0 False
[ 0.03154588  0.3691296  -0.03976994 -0.63532465] 1.0 False
[ 0.03892847  0.17458425 -0.05247643 -0.35542665] 1.0 False
[ 0.04242016  0.37041153 -0.05958496 -0.6641842 ] 1.0 False
[ 0.04982839  0.56630953 -0.07286865 -0.97501734] 1.0 False
[ 0.06115458  0.37223667 -0.09236899 -0.70608501] 1.0 False
[ 0.06859931  0.17850764 -0.1064907  -0.44384815] 1.0 False
[ 0.07216947 -0.0149591  -0.11536766 -0.18654108] 1.0 False
[ 0.07187028 -0.20825764 -0.11909848  0.06763641] 1.0 False
[ 0.06770513 -0.40148858 -0.11774575  0.32049736] 1.0 False
[ 0.05967536 -0.20490382 -0.1113358  -0.00687536] 1.0 False
[ 0.05557728 -0.00837583 -0.11147331 -0.3325073 ] 1.0 False
[ 0.055

In [ ]:
s1, reward, done, _ = env.step(a)
if done:
    Qs[0, a] = -100
else:
    x1 = np.reshape(s1, [1, input_size])
    Qs1 = sess.run(Qpred, feed_dict={X: x1})
    Qs[0, a] = reward + dis * np.max(Qs1)

In [13]:
Qs[0,a] = reward + dis * np.max(Qs1)

NameError: name 'Qs1' is not defined

In [22]:
while not done:
    step_count += 1
    x = np.reshape(s, [1, input_size])
    Qs = sess.run(Qpred, feed_dict={X: x})
    if np.random.rand(1) < e:
        a = env.action_space.sample()
    else:
        np.argmax(Qs)
    s1, reward, done, _ = env.step(a)
    if done:
        Qs[0, a] = -100
    else:
        x1 = np.reshape(s1, [1, input_size])
        Qs1 = sess.run(Qpred, feed_dict={X: x1})
        Qs[0, a] = reward + dis * np.max(Qs1)
    sess.run(train, feed_dict={X: x, Y: Qs})
    s = s1
rList.append(step_count)
print("Episode: {} steps: {}".format(i, step_count))
if len(rList) > 10 and np.mean(rList[-10:]) > 500:
    break

NameError: name 'step_count' is not defined

In [23]:
observation = env.reset()
reward_sum = 0
while True:
    env.render()
    x = np.reshape(observation, [1, input_size])
    Qs = sess.run(Qpred, feed_dict={X: x})
    a = np.argmax(Qs)
    
    observation, reward, done, _ = env.step(a)
    reward_sum += reward
    if done:
        print("Total Score: {}".format(reward_sum))
        break

NameError: name 'sess' is not defined

In [4]:
import numpy as np
import tensorflow as tf
import gym
env = gym.make('CartPole-v0')

[2017-07-28 15:33:31,747] Making new env: CartPole-v0


In [2]:
dis = .99
num_episodes = 2000
learning_rate = 0.1
input_size = env.observation_space.shape[0]
output_size = env.action_space.n
rList = []

In [5]:
X = tf.placeholder(tf.float32, [None, input_size], name="input_x")
W1 = tf.get_variable("W1", shape=[input_size, output_size], initializer=tf.contrib.layers.xavier_initializer())
Qpred = tf.matmul(X, W1)
Y = tf.placeholder(shape=[None, output_size], dtype=tf.float32)
loss = tf.reduce_sum(tf.square(Y-Qpred))
train = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)

In [7]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(num_episodes):
        e = 1. / ((i / 10) + 1)
        rAll = 0
        step_count = 0
        s = env.reset()
        done = False
        while not done:
            step_count += 1
            x = np.reshape(s, [1, input_size])
            Qs = sess.run(Qpred, feed_dict={X: x})
            if np.random.rand(1) < e:
                a = env.action_space.sample()
            else:
                np.argmax(Qs)
            s1, reward, done, _ = env.step(a)
            if done:
                Qs[0, a] = -100
            else:
                x1 = np.reshape(s1, [1, input_size])
                Qs1 = sess.run(Qpred, feed_dict={X: x1})
                Qs[0, a] = reward + dis * np.max(Qs1)
            sess.run(train, feed_dict={X: x, Y: Qs})
            s = s1

        rList.append(step_count)
        print("Episode: {} steps: {}".format(i, step_count))
        if len(rList) > 10 and np.mean(rList[-10:]) > 500:
            break
            
    observation = env.reset()
    reward_sum = 0
    while True:
        env.render()
        x = np.reshape(observation, [1, input_size])
        Qs = sess.run(Qpred, feed_dict={X: x})
        a = np.argmax(Qs)

        observation, reward, done, _ = env.step(a)
        reward_sum += reward
        if done:
            print("Total Score: {}".format(reward_sum))
            break

Episode: 0 steps: 13
Episode: 1 steps: 22
Episode: 2 steps: 13
Episode: 3 steps: 10
Episode: 4 steps: 12
Episode: 5 steps: 42
Episode: 6 steps: 9
Episode: 7 steps: 40
Episode: 8 steps: 15
Episode: 9 steps: 11
Episode: 10 steps: 17
Episode: 11 steps: 41
Episode: 12 steps: 10
Episode: 13 steps: 12
Episode: 14 steps: 49
Episode: 15 steps: 26
Episode: 16 steps: 17
Episode: 17 steps: 8
Episode: 18 steps: 9
Episode: 19 steps: 10
Episode: 20 steps: 10
Episode: 21 steps: 9
Episode: 22 steps: 8
Episode: 23 steps: 9
Episode: 24 steps: 11
Episode: 25 steps: 26
Episode: 26 steps: 22
Episode: 27 steps: 26
Episode: 28 steps: 11
Episode: 29 steps: 9
Episode: 30 steps: 10
Episode: 31 steps: 12
Episode: 32 steps: 10
Episode: 33 steps: 10
Episode: 34 steps: 22
Episode: 35 steps: 8
Episode: 36 steps: 13
Episode: 37 steps: 9
Episode: 38 steps: 9
Episode: 39 steps: 9
Episode: 40 steps: 17
Episode: 41 steps: 10
Episode: 42 steps: 9
Episode: 43 steps: 16
Episode: 44 steps: 9
Episode: 45 steps: 9
Episode: 46 

Episode: 381 steps: 22
Episode: 382 steps: 10
Episode: 383 steps: 9
Episode: 384 steps: 9
Episode: 385 steps: 10
Episode: 386 steps: 8
Episode: 387 steps: 19
Episode: 388 steps: 10
Episode: 389 steps: 9
Episode: 390 steps: 8
Episode: 391 steps: 10
Episode: 392 steps: 10
Episode: 393 steps: 9
Episode: 394 steps: 8
Episode: 395 steps: 10
Episode: 396 steps: 9
Episode: 397 steps: 8
Episode: 398 steps: 10
Episode: 399 steps: 8
Episode: 400 steps: 9
Episode: 401 steps: 9
Episode: 402 steps: 8
Episode: 403 steps: 10
Episode: 404 steps: 10
Episode: 405 steps: 9
Episode: 406 steps: 10
Episode: 407 steps: 8
Episode: 408 steps: 9
Episode: 409 steps: 10
Episode: 410 steps: 10
Episode: 411 steps: 10
Episode: 412 steps: 10
Episode: 413 steps: 11
Episode: 414 steps: 10
Episode: 415 steps: 9
Episode: 416 steps: 10
Episode: 417 steps: 8
Episode: 418 steps: 11
Episode: 419 steps: 8
Episode: 420 steps: 9
Episode: 421 steps: 10
Episode: 422 steps: 9
Episode: 423 steps: 9
Episode: 424 steps: 10
Episode: 4

Episode: 769 steps: 9
Episode: 770 steps: 8
Episode: 771 steps: 9
Episode: 772 steps: 8
Episode: 773 steps: 10
Episode: 774 steps: 9
Episode: 775 steps: 10
Episode: 776 steps: 9
Episode: 777 steps: 10
Episode: 778 steps: 10
Episode: 779 steps: 10
Episode: 780 steps: 10
Episode: 781 steps: 10
Episode: 782 steps: 12
Episode: 783 steps: 9
Episode: 784 steps: 10
Episode: 785 steps: 8
Episode: 786 steps: 9
Episode: 787 steps: 10
Episode: 788 steps: 9
Episode: 789 steps: 10
Episode: 790 steps: 10
Episode: 791 steps: 9
Episode: 792 steps: 10
Episode: 793 steps: 10
Episode: 794 steps: 10
Episode: 795 steps: 8
Episode: 796 steps: 9
Episode: 797 steps: 10
Episode: 798 steps: 9
Episode: 799 steps: 10
Episode: 800 steps: 10
Episode: 801 steps: 10
Episode: 802 steps: 9
Episode: 803 steps: 9
Episode: 804 steps: 17
Episode: 805 steps: 9
Episode: 806 steps: 8
Episode: 807 steps: 9
Episode: 808 steps: 9
Episode: 809 steps: 10
Episode: 810 steps: 9
Episode: 811 steps: 10
Episode: 812 steps: 10
Episode: 

Episode: 1136 steps: 9
Episode: 1137 steps: 8
Episode: 1138 steps: 9
Episode: 1139 steps: 10
Episode: 1140 steps: 11
Episode: 1141 steps: 10
Episode: 1142 steps: 8
Episode: 1143 steps: 9
Episode: 1144 steps: 10
Episode: 1145 steps: 9
Episode: 1146 steps: 9
Episode: 1147 steps: 9
Episode: 1148 steps: 11
Episode: 1149 steps: 8
Episode: 1150 steps: 9
Episode: 1151 steps: 8
Episode: 1152 steps: 10
Episode: 1153 steps: 9
Episode: 1154 steps: 10
Episode: 1155 steps: 10
Episode: 1156 steps: 10
Episode: 1157 steps: 9
Episode: 1158 steps: 10
Episode: 1159 steps: 10
Episode: 1160 steps: 10
Episode: 1161 steps: 10
Episode: 1162 steps: 9
Episode: 1163 steps: 9
Episode: 1164 steps: 8
Episode: 1165 steps: 8
Episode: 1166 steps: 10
Episode: 1167 steps: 10
Episode: 1168 steps: 9
Episode: 1169 steps: 10
Episode: 1170 steps: 9
Episode: 1171 steps: 9
Episode: 1172 steps: 10
Episode: 1173 steps: 10
Episode: 1174 steps: 9
Episode: 1175 steps: 10
Episode: 1176 steps: 10
Episode: 1177 steps: 10
Episode: 1178

Episode: 1506 steps: 10
Episode: 1507 steps: 10
Episode: 1508 steps: 10
Episode: 1509 steps: 9
Episode: 1510 steps: 9
Episode: 1511 steps: 9
Episode: 1512 steps: 9
Episode: 1513 steps: 9
Episode: 1514 steps: 8
Episode: 1515 steps: 10
Episode: 1516 steps: 10
Episode: 1517 steps: 9
Episode: 1518 steps: 9
Episode: 1519 steps: 10
Episode: 1520 steps: 10
Episode: 1521 steps: 9
Episode: 1522 steps: 10
Episode: 1523 steps: 10
Episode: 1524 steps: 8
Episode: 1525 steps: 9
Episode: 1526 steps: 9
Episode: 1527 steps: 8
Episode: 1528 steps: 8
Episode: 1529 steps: 10
Episode: 1530 steps: 9
Episode: 1531 steps: 22
Episode: 1532 steps: 10
Episode: 1533 steps: 9
Episode: 1534 steps: 8
Episode: 1535 steps: 9
Episode: 1536 steps: 10
Episode: 1537 steps: 10
Episode: 1538 steps: 10
Episode: 1539 steps: 11
Episode: 1540 steps: 9
Episode: 1541 steps: 9
Episode: 1542 steps: 9
Episode: 1543 steps: 10
Episode: 1544 steps: 11
Episode: 1545 steps: 10
Episode: 1546 steps: 9
Episode: 1547 steps: 10
Episode: 1548 

Episode: 1857 steps: 10
Episode: 1858 steps: 10
Episode: 1859 steps: 9
Episode: 1860 steps: 9
Episode: 1861 steps: 10
Episode: 1862 steps: 10
Episode: 1863 steps: 10
Episode: 1864 steps: 9
Episode: 1865 steps: 9
Episode: 1866 steps: 11
Episode: 1867 steps: 9
Episode: 1868 steps: 10
Episode: 1869 steps: 10
Episode: 1870 steps: 9
Episode: 1871 steps: 9
Episode: 1872 steps: 9
Episode: 1873 steps: 10
Episode: 1874 steps: 10
Episode: 1875 steps: 10
Episode: 1876 steps: 9
Episode: 1877 steps: 10
Episode: 1878 steps: 9
Episode: 1879 steps: 9
Episode: 1880 steps: 8
Episode: 1881 steps: 9
Episode: 1882 steps: 9
Episode: 1883 steps: 9
Episode: 1884 steps: 9
Episode: 1885 steps: 10
Episode: 1886 steps: 10
Episode: 1887 steps: 9
Episode: 1888 steps: 9
Episode: 1889 steps: 10
Episode: 1890 steps: 9
Episode: 1891 steps: 9
Episode: 1892 steps: 10
Episode: 1893 steps: 9
Episode: 1894 steps: 9
Episode: 1895 steps: 10
Episode: 1896 steps: 10
Episode: 1897 steps: 8
Episode: 1898 steps: 10
Episode: 1899 s